site_name: CheckID Documentation
site_description: Documentation and user guides for CheckID.no
copyright: Made on the run 🏃
site_url: https://docs.checkid.no

theme:
  name: material
  logo: assets/Logo-white.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.superfences

nav:
  - Home: index.md

  - Get Started:
      - What is CheckID?: Feature-Overview.md
      - End-User Walkthrough: Guides/User-Journey-Example.md
      - How the Flow Works: Guides/User-Journey-Detailed.md

  - Onboarding:
      - First-Time Setup: Getting-Started.md
      - Phishing-Resistant Setup: Getting-Started-Phishing-Resistant.md
      - Identity Providers: Identity-Providers/Overview.md
     # - Configure ID-porten (NO): Identity-Providers/Configure-ID-porten.md
      - Passkey Supported Devices: Guides/Supported-Devices.md

  - Configure & Customise:
      - Experience Customisation:
          - Custom Domain: Guides/Custom-Domain-Setup.md
          - Custom Branding: Guides/Custom-Branding.md
      - Identity Data & Controls:
          - Custom Security Attributes: Guides/Custom-Security-Attributes.md
          - Time Stamping: Guides/Time-Stamping.md
          - Password Blacklist: Guides/Custom-Password-Blacklist.md
          - Password Agent: Guides/Configuring-Password-Agent.md
      - Conditional Access Compatibility:
          - Authentication Strength: Conditional-Access/Authentication-Strength.md
          - Approved/Protected App Policy: Conditional-Access/Require-Approved-Or-Protected-App-Policy.md
          - Onboarding Group: Conditional-Access/Onboarding-Group.md

  - Release Notes:
      - Change Log: Change-Log.md

