site_name: CheckID Documentation
site_description: Documentation and user guides for CheckID.no
copyright: Made on the run 🏃
site_url: https://docs.checkid.no
theme:
  name: material
  logo: assets/Logo-white.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Identity Providers:
      - Norwegian BankID: Identity-Providers/Norwegian-BankID.md
      - Danish MitID: Identity-Providers/Danish-MitID.md
      - IDPorten: Identity-Providers/IDPorten.md
  - Guides and tutorials:
      - User Journey: Guides/User-Journey-Example.md
      - Custom Domain Setup: Guides/Custom-Domain-Setup.md
      - Custom Branding: Guides/Custom-Branding.md
  - Conditional access:
      - Authentication Strength: Conditional-Access/Authentication-Strength.md
      - Device Compliance: Conditional-Access/Device-Compliance.md
