site_name: CheckID Documentation
site_description: Documentation and user guides for CheckID.no
copyright: Made on the run 🏃
site_url: https://docs.checkid.no
theme:
  name: material
  logo: assets/Logo-white.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Identity Providers: Identity-Providers/Overview.md
  - Guides and tutorials:
      - User Journey Example: Guides/User-Journey-Example.md
      - Custom Domain Setup: Guides/Custom-Domain-Setup.md
      - Custom Branding: Guides/Custom-Branding.md
      - Custom Security Attributes: Guides/Custom-Security-Attributes.md
  - Conditional access:
      - Onboarding group: Conditional-Access/Onboarding-Group.md
      - Authentication strength: Conditional-Access/Authentication-Strength.md
      - Approved or protected app: Conditional-Access/Require-Approved-Or-Protected-App-Policy.md
