site_name: CheckID Documentation
site_description: Documentation and user guides for CheckID.no
copyright: Made on the run 🏃
site_url: https://docs.checkid.no

theme:
  name: material
  logo: assets/Logo-white.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.superfences

nav:
nav:
  - Home: index.md

  - Getting Started:
      - Overview: Getting-Started.md
      - Identity Providers: Identity-Providers/Overview.md
  - Using CheckID:
      - User Journey Example: Guides/User-Journey-Example.md
      - User Journey Detailed: Guides/User-Journey-Detailed.md
      - Passkey Supported Devices: Guides/Supported-Devices.md
  - Configuration:
      - Custom Domain Setup: Guides/Custom-Domain-Setup.md
      - Custom Branding: Guides/Custom-Branding.md
      - Custom Security Attributes: Guides/Custom-Security-Attributes.md
      - Custom Password Blacklist: Guides/Custom-Password-Blacklist.md
      - Password Agent Installation: Guides/Configuring-Password-Agent.md
  - Security & Access:
      - Authentication Strength: Conditional-Access/Authentication-Strength.md
      - Approved or Protected App: Conditional-Access/Require-Approved-Or-Protected-App-Policy.md
  - Release Notes: 
      - Change Log: Change-Log.md
